# frozen_string_literal: true
# Expected headers for participants.csv compared to actual in csv_spec.rb.
module ParticipantsCSV
  HEADER = ['Id', 'Email', 'Reset password sent at',
            'Remember created at', 'Sign in count', 'Current sign in at',
            'Last sign in at', 'Current sign in ip', 'Last sign in ip',
            'Confirmation token', 'Confirmed at', 'Confirmation sent at',
            'Unconfirmed email', 'Failed attempts', 'Unlock token',
            'Locked at', 'Created at', 'Updated at', 'Uuid', 'Provider', 'Uid',
            'Id [Consent response]', 'Responded at [Consent response]',
            'Is consented [Consent response]', 'Uuid [Consent response]',
            'Created at [Consent response]', 'Updated at [Consent response]',
            'Id [Daily cigarette counts]',
            'Occurred on [Daily cigarette counts]',
            'Count [Daily cigarette counts]', 'Uuid [Daily cigarette counts]',
            'Created at [Daily cigarette counts]',
            'Updated at [Daily cigarette counts]',
            'Responded at [Eligibility responses]',
            'Coded response value [Eligibility responses]',
            'Id [Eligibility status]',
            'Is eligible [Eligibility status]',
            'Created at [Eligibility status]',
            'Updated at [Eligibility status]', 'Id [Language choices]',
            'Language [Language choices]', 'Chosen at [Language choices]',
            'Uuid [Language choices]', 'Created at [Language choices]',
            'Updated at [Language choices]', 'Id [Notification schedules]',
            'Survey link [Notification schedules]',
            'Scheduled at [Notification schedules]',
            'Created at [Notification schedules]',
            'Updated at [Notification schedules]',
            'Survey index [Notification schedules]', 'Id [Page views]',
            'Occurred at [Page views]', 'Viewport width [Page views]',
            'Viewport height [Page views]', 'User agent [Page views]',
            'Language [Page views]', 'Url [Page views]',
            'Created at [Page views]', 'Updated at [Page views]',
            'Id [Participant app rating]',
            'Helpful value [Participant app rating]',
            'Rated at [Participant app rating]',
            'Created at [Participant app rating]',
            'Updated at [Participant app rating]',
            'Recommend value [Participant app rating]',
            'Id [Participant phone]', 'Phone number [Participant phone]',
            'Confirmation token [Participant phone]',
            'Confirmed at [Participant phone]',
            'Confirmation sent at [Participant phone]',
            'Uuid [Participant phone]', 'Country code [Participant phone]',
            'Mobile network code [Participant phone]',
            'Carrier name [Participant phone]',
            'Phone number type [Participant phone]',
            'Phone number validation status [Participant phone]',
            'Phone number lookup errors [Participant phone]',
            'Created at [Participant phone]', 'Updated at [Participant phone]',
            'Id [Quit dates]', 'Date [Quit dates]', 'Selected at [Quit dates]',
            'Uuid [Quit dates]', 'Created at [Quit dates]',
            'Updated at [Quit dates]'].freeze
end
